version: "3.8"

services:
  smoggler:
    image: jakubbujny/smoggler:${VERSION}
    privileged: true
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    restart: always
    volumes:
      - ./config.yaml:/opt/workdir/config.yaml
    ports:
      - "80:5000"
    environment:
      - DEV=${DEV}
